/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finlaProjectSemester04;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author isuru
 */
public class CreateAccountForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountForm
     */
    public CreateAccountForm() {
        initComponents();
         this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        otherRadio = new javax.swing.JRadioButton();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        createAdministratorAcoount = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        confirmPasswod = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        passwordOne = new javax.swing.JPasswordField();
        CancelCreateAccountForm1 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuGotoHome = new javax.swing.JMenuItem();
        CreateFormExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1041, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/D2012_292_016_1200.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Create Account for Administrator");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 460, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 90, -1));

        mobile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        mobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jPanel3.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 300, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, -1));

        firstName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jPanel3.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        lastName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel3.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        ID.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jPanel3.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 300, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 300, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        address.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 3, true));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 300, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mobile");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        otherRadio.setBackground(new java.awt.Color(0, 0, 153));
        buttonGroup1.add(otherRadio);
        otherRadio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        otherRadio.setForeground(new java.awt.Color(255, 255, 255));
        otherRadio.setText("Other");
        otherRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRadioActionPerformed(evt);
            }
        });
        jPanel3.add(otherRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 391, -1, 30));

        maleRadio.setBackground(new java.awt.Color(0, 0, 153));
        buttonGroup1.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        maleRadio.setForeground(new java.awt.Color(255, 255, 255));
        maleRadio.setText("Male");
        jPanel3.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        femaleRadio.setBackground(new java.awt.Color(0, 0, 153));
        buttonGroup1.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        femaleRadio.setForeground(new java.awt.Color(255, 255, 255));
        femaleRadio.setText("Female");
        femaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioActionPerformed(evt);
            }
        });
        jPanel3.add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        createAdministratorAcoount.setBackground(new java.awt.Color(153, 255, 255));
        createAdministratorAcoount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createAdministratorAcoount.setText("Submit");
        createAdministratorAcoount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 3, true));
        createAdministratorAcoount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdministratorAcoountActionPerformed(evt);
            }
        });
        jPanel3.add(createAdministratorAcoount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 90, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        confirmPasswod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        confirmPasswod.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 255)));
        jPanel3.add(confirmPasswod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 300, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        passwordOne.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwordOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        jPanel3.add(passwordOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 300, -1));

        CancelCreateAccountForm1.setBackground(new java.awt.Color(153, 255, 204));
        CancelCreateAccountForm1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CancelCreateAccountForm1.setText("Cancel");
        CancelCreateAccountForm1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 3, true));
        CancelCreateAccountForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelCreateAccountForm1ActionPerformed(evt);
            }
        });
        jPanel3.add(CancelCreateAccountForm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 80, 30));

        resetButton.setBackground(new java.awt.Color(255, 204, 204));
        resetButton.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel3.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, -1, -1));

        jMenu1.setBackground(new java.awt.Color(102, 204, 255));
        jMenu1.setForeground(new java.awt.Color(0, 0, 204));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Nirmala UI", 3, 18)); // NOI18N

        MenuGotoHome.setBackground(new java.awt.Color(0, 102, 102));
        MenuGotoHome.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        MenuGotoHome.setForeground(new java.awt.Color(0, 0, 204));
        MenuGotoHome.setText("Home");
        MenuGotoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGotoHomeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuGotoHome);

        CreateFormExit.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        CreateFormExit.setForeground(new java.awt.Color(0, 0, 204));
        CreateFormExit.setText("Exit");
        CreateFormExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFormExitActionPerformed(evt);
            }
        });
        jMenu1.add(CreateFormExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 51, 51));
        jMenu2.setForeground(new java.awt.Color(0, 0, 204));
        jMenu2.setText("Sign in");
        jMenu2.setFont(new java.awt.Font("Nirmala UI", 3, 18)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem3.setText("Sign in");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuGotoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGotoHomeActionPerformed
        // TODO add your handling code here:
        new HomePageForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MenuGotoHomeActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void otherRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherRadioActionPerformed

    private void createAdministratorAcoountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdministratorAcoountActionPerformed
        // TODO add your handling code here:
        String password = passwordOne.getText();
        String cPassword = confirmPasswod.getText();
        
        if(password.equals(cPassword)){
            String empID = ID.getText();
            
            if(empID.equals("")){
                JOptionPane.showMessageDialog(null, "ID is mandatory");
            }else{
                String empEmail = email.getText();
                if(empEmail.equals("")){
                    JOptionPane.showMessageDialog(null, "Email is mandatory");
                }else{
                    
                    String empFirstName = firstName.getText();
                    String empLastName = lastName.getText();
                    String empAddress = address.getText();
                    int empMobile = Integer.parseInt(mobile.getText());
                    String gender;

                    if(femaleRadio.isSelected()){
                        gender = "Female";    
                    }else if(maleRadio.isSelected()){
                        gender = "Male";
                    }else{
                        gender = "Other";   
                    }
                    ////////////pass values
//                    System.out.println(empFirstName);
//                    System.out.println(empLastName);
//                    System.out.println(empID);
//                    System.out.println(empEmail);
//                    System.out.println(empAddress);
//                    System.out.println(empMobile);
//                    System.out.println(gender);
//                    System.out.println(password);
                    try {
                        ///////////////////////////////////
                        DBConnection con = new DBConnection();
                        con.addDetailsForDatabase(empFirstName, empLastName, empID, empEmail, empAddress, empMobile, gender, password);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null,ex);
                    }
                  
                }
            }                     
        }else{
             JOptionPane.showMessageDialog(null,"Password not match..!");
        }
    }//GEN-LAST:event_createAdministratorAcoountActionPerformed
 
    private void CreateFormExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFormExitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "If you want to Exit", "Exit",               
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_CreateFormExitActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void CancelCreateAccountForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelCreateAccountForm1ActionPerformed
        // TODO add your handling code here:
        new HomePageForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelCreateAccountForm1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        firstName.setText("");
        lastName.setText("");
        ID.setText("");
        email.setText("");
        address.setText("");
        mobile.setText("");
        passwordOne.setText("");
        confirmPasswod.setText("");
        femaleRadio.setSelected(false);
        maleRadio.setSelected(false);
        otherRadio.setSelected(false);     
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccountForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountForm().setVisible(true);
            }
        });
    }
    
     private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("download.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelCreateAccountForm1;
    private javax.swing.JMenuItem CreateFormExit;
    private javax.swing.JTextField ID;
    private javax.swing.JMenuItem MenuGotoHome;
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmPasswod;
    private javax.swing.JButton createAdministratorAcoount;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lastName;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField mobile;
    private javax.swing.JRadioButton otherRadio;
    private javax.swing.JPasswordField passwordOne;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables


}
