/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finlaProjectSemester04;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Array;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author isuru
 */
public class StudentDetailsForm extends javax.swing.JFrame {

    /** Creates new form StudentDetailsForm */
    public StudentDetailsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        courseTableShow();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentDataTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        facultyComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        streemsComboBox = new javax.swing.JComboBox<>();
        idField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobileNoField = new javax.swing.JTextField();
        indexNoField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        insertStudentData = new javax.swing.JButton();
        femaleRadio = new javax.swing.JRadioButton();
        maleRadio = new javax.swing.JRadioButton();
        otherRadio = new javax.swing.JRadioButton();
        showTable = new javax.swing.JComboBox<>();
        courseComboBox = new javax.swing.JComboBox<>();
        resetDataButton = new javax.swing.JButton();
        changeData = new javax.swing.JTextField();
        dataDelete = new javax.swing.JButton();
        updateDtails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        studentDataTable.setAutoCreateRowSorter(true);
        studentDataTable.setBackground(new java.awt.Color(0, 0, 51));
        studentDataTable.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        studentDataTable.setForeground(new java.awt.Color(204, 255, 255));
        studentDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Index No", "ID No", "Full Name", "Gender", "Mobile No", "AL Streem", "Faculty", "Course Name", "Course Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studentDataTable.setCellSelectionEnabled(true);
        studentDataTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentDataTable.setGridColor(new java.awt.Color(102, 255, 153));
        studentDataTable.setSelectionBackground(new java.awt.Color(0, 153, 51));
        studentDataTable.setSelectionForeground(new java.awt.Color(0, 51, 102));
        jScrollPane2.setViewportView(studentDataTable);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 184, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faculty");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        fullNameField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fullNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel1.add(fullNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 257, 37));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Student Details");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        facultyComboBox.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        facultyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Faculty of Management", "Faculty of Information Technology", "Faculty of Science", "Faculty of Education", "Faculty of Law" }));
        facultyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(facultyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 290, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Al Streem");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Course");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        streemsComboBox.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        streemsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Physical Science stream", "Biological Science stream", "Commerce stream", "Arts stream", "Technology stream" }));
        streemsComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        streemsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streemsComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(streemsComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 170, -1));

        idField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 257, 37));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        mobileNoField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mobileNoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(mobileNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 257, 37));

        indexNoField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        indexNoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jPanel1.add(indexNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 257, 37));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Index No");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        insertStudentData.setBackground(new java.awt.Color(204, 255, 204));
        insertStudentData.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        insertStudentData.setText("Insert");
        insertStudentData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        insertStudentData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertStudentDataActionPerformed(evt);
            }
        });
        jPanel1.add(insertStudentData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 80, -1));

        femaleRadio.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        femaleRadio.setForeground(new java.awt.Color(255, 255, 255));
        femaleRadio.setText("Female");
        femaleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioActionPerformed(evt);
            }
        });
        jPanel1.add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        maleRadio.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        maleRadio.setForeground(new java.awt.Color(255, 255, 255));
        maleRadio.setText("Male");
        jPanel1.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        otherRadio.setBackground(new java.awt.Color(0, 0, 102));
        buttonGroup1.add(otherRadio);
        otherRadio.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        otherRadio.setForeground(new java.awt.Color(255, 255, 255));
        otherRadio.setText("Other");
        otherRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRadioActionPerformed(evt);
            }
        });
        jPanel1.add(otherRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, 30));

        showTable.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        showTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select faculty to show Details", "All", "Faculty of Management", "Faculty of Information Technology", "Faculty of Science", "Faculty of Education", "Faculty of Law" }));
        showTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTableActionPerformed(evt);
            }
        });
        jPanel1.add(showTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 290, -1));

        courseComboBox.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "BSc in Business Management", "Bachelor of Management (Hons) in Marketing", "BSc (Hons) in Information Technology", "BIT (Hons) in Networking & Mobile Computing", "BSc in Biotechnology", "Bachelor of Education (BEd)", "Bachelor of LAW (LLB)" }));
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(courseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 290, -1));

        resetDataButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        resetDataButton.setText("Reset");
        resetDataButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        resetDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetDataButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 80, 30));

        changeData.setBackground(new java.awt.Color(204, 204, 255));
        changeData.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        changeData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        changeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDataActionPerformed(evt);
            }
        });
        jPanel1.add(changeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 130, 30));

        dataDelete.setBackground(new java.awt.Color(255, 255, 204));
        dataDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dataDelete.setText("Delete");
        dataDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(102, 0, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 102, 102)));
        dataDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(dataDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 80, 30));

        updateDtails.setBackground(new java.awt.Color(255, 255, 204));
        updateDtails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateDtails.setText("Update");
        updateDtails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(102, 0, 102), new java.awt.Color(51, 51, 51), new java.awt.Color(0, 102, 102)));
        updateDtails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDtailsActionPerformed(evt);
            }
        });
        jPanel1.add(updateDtails, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 80, 30));

        courseTable.setAutoCreateRowSorter(true);
        courseTable.setBackground(new java.awt.Color(0, 0, 51));
        courseTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        courseTable.setForeground(new java.awt.Color(255, 255, 204));
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name"
            }
        ));
        courseTable.setAlignmentX(1.0F);
        courseTable.setAlignmentY(10.0F);
        courseTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        courseTable.setRowHeight(24);
        courseTable.setRowMargin(3);
        courseTable.setSelectionBackground(new java.awt.Color(102, 0, 102));
        courseTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        courseTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(courseTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 400, 250));

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setText("Index Number");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 120, 30));

        jMenu1.setBackground(new java.awt.Color(0, 0, 153));
        jMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 0)));
        jMenu1.setForeground(new java.awt.Color(51, 51, 255));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Nirmala UI", 3, 18)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(51, 255, 204));
        jMenuItem1.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem1.setText("Home");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(0, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void courseTableShow(){
        JTableHeader header= courseTable.getTableHeader();
        header.setForeground(Color.DARK_GRAY);
        header.setFont(new Font(null,Font.BOLD,18));
      
        TableColumn col = courseTable.getColumnModel().getColumn(0);
        col.setPreferredWidth(130);
        TableColumn col2 = courseTable.getColumnModel().getColumn(1);
        col2.setPreferredWidth(350);
        
        
        
        
        try {
            DBConnection con = new DBConnection();
            ArrayList<GetData> ctdata =  con.getCourseDtailsToTable();
            DefaultTableModel model = (DefaultTableModel) courseTable.getModel();
            Object[] row = new Object[2];
            for(int i = 0;i<ctdata.size();i++){
                row[0] = ctdata.get(i).getcCode();
                row[1] = ctdata.get(i).getcName();
                model.addRow(row);
            }

        } catch (SQLException ex) {
            Logger.getLogger(StudentDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void showTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTableActionPerformed
       
        DefaultTableModel model = (DefaultTableModel) studentDataTable.getModel();
        model.setRowCount(0);
        ArrayList<GetData> getData;
        try {
            DBConnection con = new DBConnection();
            String sqlQuery;

            if("All".equals(showTable.getItemAt(showTable.getSelectedIndex()))){
                getData=con.getDataToTheTable("SELECT * FROM `student`");
                showTable(getData);
            }else{
                getData= con.getDataToTheTable("SELECT * FROM `student` WHERE faculty ='"+showTable.getItemAt(showTable.getSelectedIndex())+"'");
                showTable(getData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(StudentDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showTableActionPerformed

    private void otherRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherRadioActionPerformed

    private void femaleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioActionPerformed

    private void insertStudentDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertStudentDataActionPerformed
        // TODO add your handling code here:

        String index = indexNoField.getText();
        String id = idField.getText();
        String fullName = fullNameField.getText();
        int mobileNo = Integer.parseInt(mobileNoField.getText());
        String gender;
        if(femaleRadio.isSelected()){
            gender = "Female";
        }else if(maleRadio.isSelected()){
            gender = "Male";
        }else{
            gender = "Other";
        }
        String streems = streemsComboBox.getItemAt(streemsComboBox.getSelectedIndex());
        String faculty = facultyComboBox.getItemAt(facultyComboBox.getSelectedIndex());
        String course =  courseComboBox.getItemAt(courseComboBox.getSelectedIndex());

        //        System.out.println(index);
        //        System.out.println(id);
        //        System.out.println(fullName);
        //        System.out.println(mobileNo);
        //        System.out.println(gender);
        //        System.out.println(streems);
        //        System.out.println(faculty);
        //        System.out.println(course);

        DBConnection con;
        try {
            con = new DBConnection();
            con.addStudentDataIntoDatabase(index, id, fullName, mobileNo, gender, streems, faculty, course);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_insertStudentDataActionPerformed

    private void streemsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streemsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streemsComboBoxActionPerformed

    private void facultyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyComboBoxActionPerformed

    private void resetDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetDataButtonActionPerformed
        // TODO add your handling code here:
         indexNoField.setText("");
         idField.setText("");
         fullNameField.setText("");
         mobileNoField.setText("");

    }//GEN-LAST:event_resetDataButtonActionPerformed

    private void dataDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDeleteActionPerformed
        // TODO add your handling code here:
        String index = changeData.getText();
        try {
            DBConnection con = new DBConnection();
            con.dataDeleteFromDatabase(index);
        } catch (SQLException ex) {
            Logger.getLogger(StudentDetailsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataDeleteActionPerformed

    private void updateDtailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDtailsActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_updateDtailsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
          new HomePageForm().setVisible(true);
          this.setVisible(false);          
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         JFrame frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "If you want to Exit", "Exit",               
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void changeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeDataActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
   void showTable(ArrayList<GetData> dataList){
      DefaultTableModel model = (DefaultTableModel)studentDataTable.getModel();
      Object[] row = new Object[10];
      int count=0;
      for(int i=0;i<dataList.size();i++){
          row[0] = ++count;
          row[1] = dataList.get(i).getIndexNo();
          row[2] = dataList.get(i).getStuId();
          row[3] = dataList.get(i).getFullName();
          row[4] = dataList.get(i).getGender();
          row[5] = dataList.get(i).getMobile();
          row[6] = dataList.get(i).getStreem();
          row[7] = dataList.get(i).getFaculty();
          row[8] = dataList.get(i).getCourseName();
          row[9] = dataList.get(i).getCourseCode();  
          model.addRow(row);

      }     
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetailsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetailsForm().setVisible(true);
            }
        });
    }
    
     private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("download.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField changeData;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton dataDelete;
    private javax.swing.JComboBox<String> facultyComboBox;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField indexNoField;
    private javax.swing.JButton insertStudentData;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField mobileNoField;
    private javax.swing.JRadioButton otherRadio;
    private javax.swing.JButton resetDataButton;
    private javax.swing.JComboBox<String> showTable;
    private javax.swing.JComboBox<String> streemsComboBox;
    private javax.swing.JTable studentDataTable;
    private javax.swing.JButton updateDtails;
    // End of variables declaration//GEN-END:variables

}
